openapi: 3.0.0
info:
  title: Standup Buddy API
  description: API for keeping track of standup meeting updates.
  version: 1.0.0
servers:
  - url: https://standup-buddy.herokuapp.com/api
paths:
  /teams:
    get:
      summary: Returns a list of teams.
      responses:
        '200':
          description: A JSON array of items
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string